const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{readFileSync}=require('node:fs');
function fixture(){const instances=[];function element(){const classes=new Set();return {isConnected:true,children:[],listeners:{},classList:{add(...v){v.forEach(c=>classes.add(c));},remove(...v){v.forEach(c=>classes.delete(c));},contains:c=>classes.has(c)},append(child){child.parent=this;this.children.push(child);},remove(){this.parent=null;},querySelector(selector){return this.children.find(c=>'.'+c.className===selector);},addEventListener(kind,fn){this.listeners[kind]=fn;}};}
 class Panorama{constructor(root,options){this.root=root;this.pano=options.pano;this.pov=options.pov;this.zoom=options.zoom;this.listeners={};instances.push(this);}addListener(k,fn){this.listeners[k]=fn;}getPov(){return this.pov;}getZoom(){return this.zoom;}getPano(){return this.pano;}getStatus(){return 'OK';}setPano(p){this.pano=p;}setPov(p){this.pov=p;this.listeners.pov_changed?.();}setZoom(z){this.zoom=z;this.listeners.zoom_changed?.();}setVisible(v){this.visible=v;}}
 const window={google:{maps:{StreetViewPanorama:Panorama,StreetViewStatus:{OK:'OK'},event:{trigger(){}}}}},context={window,URL,URLSearchParams,Math,Promise,Number,Date,document:{createElement:element},setTimeout,clearTimeout};vm.runInNewContext(readFileSync('photo-scout-site/street-view.js','utf8'),context);vm.runInNewContext(readFileSync('photo-scout-site/native-street-view.js','utf8'),context);
 function options(pano){const spot={provider:'google-street-view',sourceUrl:`https://www.google.com/maps/@?map_action=pano&pano=${pano}&heading=90&pitch=0&fov=90`};return {spot,getSpot:()=>spot,onChange(v){spot.viewHeadingDegrees=v.heading;spot.viewPitchDegrees=v.pitch;spot.viewFovDegrees=v.fov;}};}
 return {helper:window.PhotoScoutNativeStreetView,element,instances,options};}
test('switching surfaces reuses the panorama and preserves native edits without image requests',async()=>{const f=fixture(),a=f.element(),b=f.element(),first=f.options('one'),second=f.options('two');await f.helper.attach(a,first);f.instances[0].root.listeners.pointerdown({});f.instances[0].setPov({heading:135,pitch:20});assert.equal(first.spot.viewHeadingDegrees,135);assert.equal(first.spot.viewPitchDegrees,20);await f.helper.attach(b,second);assert.equal(f.instances.length,1);assert.equal(f.instances[0].pano,'two');assert.equal(f.helper.isActive(a),false);assert.equal(f.helper.isActive(b),true);f.helper.detach(a);assert.equal(f.helper.isActive(b),true);f.helper.detach(b);assert.equal(f.instances[0].visible,false);});
test('closing before initialization finishes does not create a hidden billable panorama',async()=>{const f=fixture(),surface=f.element();const loading=f.helper.attach(surface,f.options('one'));f.helper.detach(surface);assert.equal(await loading,false);assert.equal(f.instances.length,0);});
test('native zoom stays within the static background range, and keyboard controls update the same view',async()=>{const f=fixture(),surface=f.element(),o=f.options('one');await f.helper.attach(surface,o);const p=f.instances[0];p.root.listeners.pointerdown({});p.setZoom(9);assert.equal(o.spot.viewFovDegrees,30);assert.equal(f.helper.fovForZoom(p.zoom),30);p.root.listeners.keydown({key:'ArrowRight',preventDefault(){},stopImmediatePropagation(){}});assert.equal(o.spot.viewHeadingDegrees,105);for(const fov of [30,45,60,90,120])assert.equal(f.helper.fovForZoom(f.helper.zoomForFov(fov)),fov);});

test('SDK initialization changes do not silently replace Auto or a commanded framing',async()=>{const f=fixture(),surface=f.element(),o=f.options('one');await f.helper.attach(surface,o);f.instances[0].setZoom(1.426);assert.equal(o.spot.viewFovDegrees,undefined);assert.equal(o.spot.sourceUrl.includes('fov=90'),true);f.helper.detach(surface);});
