const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{readFileSync}=require('node:fs');
function fixture(getUserMedia){
 const elements=[];
 function element(){const children=new Map(),events={};const e={open:false,disabled:false,videoWidth:640,videoHeight:480,files:[],textContent:'',setAttribute(){},append(){},addEventListener(k,f){events[k]=f;},querySelector(k){if(!children.has(k))children.set(k,element());return children.get(k);},showModal(){this.open=true;},close(){this.open=false;events.close?.();},async play(){},click(){this.onclick?.();}};elements.push(e);return e;}
 const context={window:{},navigator:{mediaDevices:{getUserMedia}},document:{createElement:element,body:{append(){}}}};vm.runInNewContext(readFileSync('photo-scout-site/camera.js','utf8'),context);return new context.window.PhotoScoutCamera(()=>{});
}
function stream(){const track={stopped:false,stop(){this.stopped=true;}};return {track,getTracks:()=>[track]};}
test('closing camera preview immediately releases its video track',async()=>{const s=stream(),camera=fixture(async()=>s);await camera.open();assert.equal(camera.capture.disabled,false);camera.dialog.querySelector('[data-camera=close]').click();assert.equal(s.track.stopped,true);assert.equal(camera.video.srcObject,null);});
test('camera permission completing after dialog closure cannot leak a live stream',async()=>{let grant;const s=stream(),camera=fixture(()=>new Promise(resolve=>grant=resolve));const pending=camera.open();camera.dialog.close();grant(s);await pending;assert.equal(s.track.stopped,true);assert.equal(camera.video.srcObject,null);});
test('a late previous camera session cannot replace a newly opened preview',async()=>{const grants=[],camera=fixture(()=>new Promise(resolve=>grants.push(resolve))),first=stream(),second=stream();const a=camera.open();camera.dialog.close();const b=camera.open();grants[1](second);await b;grants[0](first);await a;assert.equal(first.track.stopped,true);assert.equal(second.track.stopped,false);assert.equal(camera.stream,second);camera.stop();});
test('denied camera permission keeps native capture fallback available',async()=>{const camera=fixture(async()=>{throw Object.assign(new Error(),{name:'NotAllowedError'});});await camera.open();assert.equal(camera.capture.disabled,true);assert.match(camera.status.textContent,/not granted/);assert.equal(camera.dialog.open,true);assert.equal(camera.native.type,'file');});
