const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{readFileSync}=require('node:fs');
function fixture(){const source=readFileSync('photo-scout-site/app.js','utf8'),saves=[];const scope={taskRecoveryGeneration:1,studioUploadGeneration:0,studioLibraryStatus:{textContent:'',replaceChildren(...nodes){this.textContent=nodes.map(n=>n.textContent).join('')}},studioFile:null,studioPrepared:null,personPreview:{removeAttribute(){}},studioGenerate:{},studioPreviewUrl:null,studioBusy:false,studioStatus:{},prepareStudioPhoto:async()=>({data:'prepared',preview:true}),avatarLibrary:{saveUpload:async(file,prepared)=>{saves.push({file,prepared});return {id:'saved'}}},node:(tag,text)=>({textContent:text})};vm.runInNewContext(source.slice(source.indexOf('async function acceptStudioPhoto('),source.indexOf('async function prepareStudioPhoto(')),scope);return {scope,saves};}
const file={name:'my-selfie.jpg',size:100,type:'image/jpeg'};const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('own uploaded or captured photo saves prepared bytes without blocking selfie readiness',async()=>{const {scope,saves}=fixture();await scope.acceptStudioPhoto(file);await settle();assert.equal(saves.length,1);assert.equal(saves[0].prepared.data,'prepared');assert.equal(scope.studioPrepared,'prepared');assert.equal(scope.studioGenerate.disabled,false);assert.match(scope.studioLibraryStatus.textContent,/Saved privately/);});
test('choosing an existing library image does not auto-save another copy',async()=>{const {scope,saves}=fixture();await scope.acceptStudioPhoto(file,{saveToLibrary:false});assert.equal(saves.length,0);assert.equal(scope.studioPrepared,'prepared');});
test('library failure still permits this selfie and reports the saving failure',async()=>{const {scope}=fixture();scope.avatarLibrary.saveUpload=async()=>{throw Error('Library full')};await scope.acceptStudioPhoto(file);await settle();assert.equal(scope.studioGenerate.disabled,false);assert.match(scope.studioLibraryStatus.textContent,/could not be saved.*Library full/);});
test('switching places or accounts prevents late save results changing the new studio',async()=>{const {scope}=fixture();let finish;scope.avatarLibrary.saveUpload=()=>new Promise(resolve=>finish=resolve);await scope.acceptStudioPhoto(file);scope.studioUploadGeneration++;scope.taskRecoveryGeneration++;scope.studioLibraryStatus.textContent='New scene';finish({id:'old'});await settle();assert.equal(scope.studioLibraryStatus.textContent,'New scene');});
test('account switch during photo preparation cancels auto-save and preview application',async()=>{const {scope,saves}=fixture();let finish;scope.prepareStudioPhoto=()=>new Promise(resolve=>finish=resolve);const task=scope.acceptStudioPhoto(file);scope.taskRecoveryGeneration++;finish({data:'old',preview:true});await task;assert.equal(saves.length,0);assert.equal(scope.studioPrepared,null);});
test('late library save cannot populate the next account or duplicate an existing item',async()=>{const scope={window:{}};vm.runInNewContext(readFileSync('photo-scout-site/avatars.js','utf8'),scope);let session={id:'alice',epoch:1},finish;const library=Object.create(scope.window.PhotoScoutAvatars.prototype);Object.assign(library,{items:[{id:'same'}],tab:'presets',session:()=>session,request:()=>new Promise(resolve=>finish=resolve)});const saved=library.saveUpload(file,{data:'bytes'});session={id:'bob',epoch:2};finish({id:'alice-photo'});assert.equal(await saved,null);assert.equal(library.items[0].id,'same');library.request=async()=>({id:'same'});await library.saveUpload(file,{data:'bytes'});assert.equal(library.items.length,1);});
