const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function fixture(webgl=true){const frames=[],draws=[];const gl={createShader:()=>({}),getShaderParameter:()=>true,createProgram:()=>({}),getProgramParameter:()=>true,createBuffer:()=>({}),getAttribLocation:()=>0,createTexture:()=>({}),getUniformLocation:(_,n)=>n,uniform3fv(n,v){this[n]=Array.from(v);},drawArrays(){draws.push(this.forward);}};for(const name of ['shaderSource','compileShader','attachShader','linkProgram','deleteShader','useProgram','bindBuffer','bufferData','enableVertexAttribArray','vertexAttribPointer','bindTexture','texParameteri','texImage2D','viewport','uniform1f','deleteTexture','deleteBuffer','deleteProgram'])gl[name]=()=>{};
 function element(){return {isConnected:true,classList:{add(){},remove(){}},children:[],getBoundingClientRect:()=>({width:320,height:200}),getContext:()=>webgl?gl:null,setAttribute(){},append(...n){this.children.push(...n);},remove(){this.isConnected=false;},addEventListener(){}};}
 const window={devicePixelRatio:1,requestAnimationFrame(fn){frames.push(fn);return frames.length;},cancelAnimationFrame(){},PhotoScoutStreetView:{view:s=>({heading:s.heading||0,pitch:0,fov:90})}};
 vm.runInNewContext(fs.readFileSync('photo-scout-site/panorama-view.js','utf8'),{window,URL,Math,Date,Float32Array,document:{createElement:element},Image:class{async decode(){}}});
 const spot={provider:'google-street-view',sourceUrl:'https://www.google.com/maps/@?pano=one',heading:0},payload={image:'data:fixture',expiresAt:9999999999,heading:0,tilt:90,roll:0,copyright:'Fixture'};return {helper:window.PhotoScoutLocalPanorama,frames,draws,element,spot,payload};}
test('one sphere is shared across surfaces and repeated camera changes coalesce into animation frames without fetching',async()=>{const f=fixture(),a=f.element(),b=f.element();let loads=0;const options={getSpot:()=>f.spot,loadPanorama:async()=>{loads++;return f.payload;}};await Promise.all([f.helper.attach(a,options),f.helper.attach(b,options)]);assert.equal(loads,1);const before=f.draws.length;for(let n=0;n<100;n++){f.spot.heading=n;assert.equal(f.helper.refresh(a),true);}assert.equal(f.frames.length,1);f.frames[0]();assert.equal(f.draws.length,before+1);assert.equal(loads,1);assert.ok(Math.abs(f.draws.at(-1)[0]-Math.sin(99*Math.PI/180))<1e-6);});
test('a source change during loading cannot paint the previous panorama into the next scene',async()=>{const f=fixture(),a=f.element();let release;const loading=f.helper.attach(a,{getSpot:()=>f.spot,loadPanorama:()=>new Promise(resolve=>release=resolve)});await Promise.resolve();f.spot.sourceUrl='https://www.google.com/maps/@?pano=two';release(f.payload);assert.equal(await loading,false);assert.equal(f.helper.isActive(a),false);assert.equal(f.draws.length,0);});
test('a closed surface never draws a late response',async()=>{const f=fixture(),a=f.element();let release;const loading=f.helper.attach(a,{getSpot:()=>f.spot,loadPanorama:()=>new Promise(resolve=>release=resolve)});await Promise.resolve();f.helper.detach(a);release(f.payload);assert.equal(await loading,false);assert.equal(f.draws.length,0);});
test('unsupported browsers fall back without fetching or creating paid native views',async()=>{const f=fixture(false);let loads=0;assert.equal(await f.helper.attach(f.element(),{getSpot:()=>f.spot,loadPanorama:async()=>{loads++;return f.payload;}}),false);assert.equal(loads,0);});
test('expired sphere responses are not reused for a new surface',async()=>{const f=fixture();let loads=0;const options={getSpot:()=>f.spot,loadPanorama:async()=>{loads++;return {...f.payload,expiresAt:1};}};await f.helper.attach(f.element(),options);await f.helper.attach(f.element(),options);assert.equal(loads,2);});
test('compass basis matches backend orientation at the poles and rotated horizons',()=>{const f=fixture();for(const [h,p,r] of [[0,0,0],[90,0,0],[180,90,30],[359,-90,-20]]){const b=f.helper.basis(h,p,r);for(const v of Object.values(b))assert.ok(Math.abs(v.reduce((s,n)=>s+n*n,0)-1)<1e-6);assert.ok(Math.abs(b.forward.reduce((s,n,i)=>s+n*b.right[i],0))<1e-6);}assert.ok(Math.abs(f.helper.basis(90,0).forward[0]-1)<1e-6);});
