'use strict';
const api=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'': 'https://api.aisoup.net';
const el=id=>document.getElementById(id), message=s=>{el('message').textContent=s};
const map=L.map('map').setView([41.8827,-87.6233],15);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
let selected=L.marker([41.8827,-87.6233]).addTo(map), resultPins=[];let humanFreePreview=false;
function pick(lat,lon){el('lat').value=lat.toFixed(6);el('lon').value=lon.toFixed(6);selected.setLatLng([lat,lon]);}
map.on('click',e=>pick(e.latlng.lat,e.latlng.lng));
for(const id of ['lat','lon']) el(id).addEventListener('change',()=>{const lat=Number(el('lat').value),lon=Number(el('lon').value);if(Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=85&&Math.abs(lon)<=180){selected.setLatLng([lat,lon]);map.setView([lat,lon],15)}});
function node(tag,txt,cls){const n=document.createElement(tag);if(txt)n.textContent=txt;if(cls)n.className=cls;return n;}
function link(label,url){const n=node('a',label);try{const u=new URL(url);if(u.protocol!=='https:')return node('span',label);n.href=u.href;n.target='_blank';n.rel='noopener noreferrer';}catch{return node('span',label)}return n;}
function render(result){const root=el('results');root.replaceChildren(node('h2','Your nearby photo shortlist'),node('p',result.summary));const cards=node('div',null,'cards');root.append(cards);resultPins.forEach(p=>p.remove());resultPins=[];
 for(const [i,s] of (result.spots||[]).entries()){const card=node('article',null,'card');if(s.imageUrl&&s.provider!=='google-street-view'){const img=node('img');img.src=s.imageUrl;img.alt=s.name;img.loading='lazy';img.referrerPolicy='no-referrer';card.append(img);}else if(s.provider==='google-street-view'){const view=link('Explore this view in Google Street View ↗',s.sourceUrl);view.className='street-view-link';card.append(view);}const body=node('div',null,'body');body.append(node('h3',`${i+1}. ${s.name}`),node('span',`${s.score}/100 subjective photo score · ${s.confidence} confidence`,'tag'),node('p',`Image source: ${s.provider}`,'small'),node('p',s.visible_evidence),node('p',`Photo idea: ${s.photo_tip}`),...(s.viewHeadingDegrees!=null?[node('p',`Inspected camera direction: ${s.viewHeadingDegrees}°`,'small')]:[]),node('p',`${s.distanceMeters} m straight-line distance · ${s.locationType}`),node('p',`Uncertainty: ${s.uncertainty}`),node('p',s.coordinateWarning),link(s.provider==='google-street-view'?'View Google Street View ↗':'Original image ↗',s.sourceUrl),node('p',`${s.author} · ${s.license} · source date: ${s.sourceDate||s.capturedAt||'unknown'}`),link('Image license ↗',s.licenseUrl));card.append(body);cards.append(card);const p=L.marker([s.lat,s.lon]).addTo(map).bindPopup(node('span',s.name));resultPins.push(p);}
 if(result.nearbyPois?.length){root.append(node('h3','Other nearby points of interest'),node('p','OpenStreetMap entries below have not been visually assessed by the agent.'));const list=node('ul');for(const p of result.nearbyPois){const li=node('li');li.append(link(`${p.name} · ${p.category} · ${p.distanceMeters} m ↗`,p.sourceUrl));list.append(li);}root.append(list,node('p','© OpenStreetMap contributors · ODbL 1.0','small'));}
 if(result.sources){const coverage=node('p',Object.entries(result.sources).map(([name,s])=>`${name}: ${s.status==='ok'?(s.eligibleImages!==undefined?`${s.eligibleImages} eligible images sampled`:'available'):'temporarily unavailable'}`).join(' · '),'small');root.append(coverage);}
 root.append(node('p',`Inspected ${result.inspectedImages} images${result.inspectedImageSources?.length?" from "+result.inspectedImageSources.join(", "):""}. ${result.coverage}`,'small'));root.scrollIntoView({behavior:'smooth'});}
async function json(url,options){const r=await fetch(api+url,options),data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Request failed');return data;}
async function poll(job){const token=sessionStorage.getItem('photo-scout:'+job);if(!token){message('Open this report in the original checkout tab. Your private report token is stored only in that tab.');return;}el('submit').disabled=true;message('Confirming payment and exploring nearby images…');for(let n=0;n<80;n++){try{const d=await json('/photo-scout/v1/report/'+encodeURIComponent(job),{headers:{'X-Report-Token':token}});if(d.state==='complete'){render(d.result);message('Your report is ready.');return;}if(d.state==='failed')message(d.error||'Retrying exploration…');}catch(e){message(e.message);return;}await new Promise(r=>setTimeout(r,5000));}message('Still processing. Refresh to check your report; no new payment is needed.');}
el('search').addEventListener('submit',async e=>{e.preventDefault();el('submit').disabled=true;message(humanFreePreview?'Exploring nearby images… This may take a few minutes.':'Checking image coverage before checkout…');try{const d=await json(humanFreePreview?'/photo-scout/v1/preview':'/photo-scout/v1/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:Number(el('lat').value),lon:Number(el('lon').value),radius:Number(el('radius').value),limit:3,preferences:el('preferences').value})});if(humanFreePreview){render(d);message('Your free test is ready. Results stay on this page until you refresh.');}else{sessionStorage.setItem('photo-scout:'+d.jobId,d.reportToken);location.assign(d.checkoutUrl);}}catch(err){message(err.message);}finally{el('submit').disabled=false;}});
(async()=>{try{const s=await json('/photo-scout/v1/status');humanFreePreview=s.humanFreePreview===true;el('submit').textContent=s.enabled&&humanFreePreview?'Find photo spots · Free test':s.enabled&&s.humanPriceUsd?`Find photo spots · $${s.humanPriceUsd}`:'Exploration coming soon';el('submit').disabled=!(s.enabled&&(humanFreePreview||s.humanPriceUsd));el('test-notice').hidden=!humanFreePreview;const q=new URLSearchParams(location.search);if(q.get('job'))await poll(q.get('job'));}catch{message('The service is temporarily unavailable.');}})();

el('sample').addEventListener('click',async()=>{try{const r=await fetch('./sample.json');if(!r.ok)throw Error('Sample unavailable');const data=await r.json();map.setView([41.8827,-87.6233],14);render(data);}catch(e){message(e.message)}});

el('sample-paris').addEventListener('click',async()=>{try{const r=await fetch('./sample-paris.json');if(!r.ok)throw Error('Sample unavailable');map.setView([48.855,2.295],15);render(await r.json());}catch(e){message(e.message)}});

el("sample-google").addEventListener("click",async()=>{try{const r=await fetch("./sample-google.json");if(!r.ok)throw Error("Sample unavailable");const data=await r.json();map.setView([48.8603,2.2919],16);render(data);message(data.sampleNotice);}catch(e){message(e.message)}});
