/* Shared private-library UI, with an explicit selection for each selfie scene. */
window.PhotoScoutAvatars=class {
 constructor({api,request,prepare,onSelect,session,canSelect}){
  Object.assign(this,{api,request,prepare,onSelect,session,canSelect});this.generation=0;this.items=[];this.presetItems=[];this.tab='mine';this.loaded=false;
  this.menu=document.getElementById('avatar-library');this.panel=this.menu.querySelector('.avatar-content');this.dialog=document.createElement('dialog');this.dialog.className='photo-studio avatar-picker';this.dialog.setAttribute('aria-label','Choose an avatar');document.body.append(this.dialog);
  this.menu.addEventListener('toggle',()=>{if(this.menu.open)this.load(this.panel);});this.dialog.addEventListener('close',()=>{this.generation++;});this.render(this.panel);
 }
 reset(){this.generation++;this.items=[];this.loaded=false;this.dialog.close();this.render(this.panel);}
 async load(root){const generation=++this.generation;this.render(root,'Loading your library…');try{const [data,presets]=await Promise.all([this.request('/photo-scout/v1/avatars'),this.presetItems.length?Promise.resolve({items:this.presetItems}):fetch('./avatars/presets.json').then(r=>{if(!r.ok)throw Error('Preset library unavailable');return r.json();})]);if(generation!==this.generation)return;this.items=data.items;this.presetItems=presets.items;this.loaded=true;this.render(root);}catch(error){if(generation===this.generation)this.render(root,error.message);}}
 open(){this.menu.open=false;this.tab='mine';this.render(this.dialog);this.dialog.showModal();this.load(this.dialog);}
 render(root,message=''){
  root.replaceChildren();if(root===this.dialog){const top=document.createElement('div');top.className='studio-heading';top.innerHTML='<h2>Choose an avatar</h2><button type="button">Close ×</button>';top.querySelector('button').onclick=()=>this.dialog.close();root.append(top);}
  const tabs=document.createElement('div');tabs.className='avatar-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Avatar collections');
  for(const [id,title] of [['mine','My uploads'],['presets','Preset characters']]){const button=document.createElement('button');button.type='button';button.textContent=title;button.setAttribute('role','tab');button.setAttribute('aria-selected',String(this.tab===id));button.onclick=()=>{this.tab=id;this.render(root);};tabs.append(button);}root.append(tabs);
  const status=document.createElement('p');status.className='avatar-status small';status.setAttribute('role','status');status.textContent=message;root.append(status);
  if(this.tab==='mine'){
   const form=document.createElement('form');form.className='avatar-upload';const name=document.createElement('input');name.type='text';name.placeholder='Avatar name (optional)';name.maxLength=80;name.setAttribute('aria-label','Avatar name');const file=document.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif';file.setAttribute('aria-label','Upload an avatar');const submit=document.createElement('button');submit.type='submit';submit.textContent='Upload avatar';form.append(name,file,submit);root.append(form);
   form.onsubmit=async event=>{event.preventDefault();if(!file.files[0]){status.textContent='Choose a photo first.';return;}const generation=this.generation,identity=this.session().id;submit.disabled=true;status.textContent='Preparing and saving your avatar…';try{const source=file.files[0];if(source.size>20000000)throw Error('Choose a photo up to 20 MB.');const prepared=await this.prepare(source);if(!prepared.preview)throw Error('Export this image as JPG or PNG, then upload it.');if(generation!==this.generation||identity!==this.session().id)return;await this.request('/photo-scout/v1/avatars',{method:'POST',headers:this.headers(),body:JSON.stringify({name:name.value.trim()||source.name.replace(/\.[^.]+$/,'' ).slice(0,80)||'My avatar',image:prepared.data})});if(generation===this.generation&&identity===this.session().id)await this.load(root);}catch(error){if(generation===this.generation)status.textContent=error.message;}finally{submit.disabled=false;}};
  }
  const grid=document.createElement('div');grid.className='avatar-grid';const items=this.tab==='mine'?this.items:this.presetItems;
  for(const item of items){const card=document.createElement('div');card.className='avatar-card';const pick=document.createElement('button');pick.type='button';pick.className='avatar-pick';pick.title='Use '+item.name+' in your selfie';const img=document.createElement('img');img.alt=item.name;img.loading='lazy';img.src=this.tab==='mine'?this.api+item.imageUrl:item.imageUrl;const title=document.createElement('span');title.textContent=item.name;pick.append(img,title);card.append(pick);
   pick.onclick=async()=>{if(!this.canSelect()){status.textContent='Open Take a selfie at a photo spot, then choose an avatar there.';return;}const generation=this.generation,identity=this.session().id;pick.disabled=true;status.textContent='Preparing '+item.name+'…';try{const response=await fetch(img.src,{credentials:this.tab==='mine'?'include':'same-origin'});if(!response.ok)throw Error('Could not load this avatar. Please try again.');const blob=await response.blob();const png=blob.type.includes('svg')?await this.rasterize(blob):blob;if(generation!==this.generation||identity!==this.session().id)return;await this.onSelect(new File([png],item.name+(png.type==='image/png'?'.png':'.jpg'),{type:png.type}));if(generation===this.generation){if(root===this.dialog)this.dialog.close();else this.menu.open=false;}}catch(error){if(generation===this.generation)status.textContent=error.message;}finally{pick.disabled=false;}};
   if(this.tab==='mine'){const remove=document.createElement('button');remove.type='button';remove.className='avatar-remove';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+item.name);remove.onclick=async()=>{remove.disabled=true;const generation=this.generation;try{await this.request('/photo-scout/v1/avatars/'+encodeURIComponent(item.id),{method:'DELETE',headers:this.headers()});if(generation===this.generation)await this.load(root);}catch(error){if(generation===this.generation)status.textContent=error.message;}finally{remove.disabled=false;}};card.append(remove);}grid.append(card);
  }root.append(grid);
  if(!items.length&&!message){status.textContent=this.tab==='mine'?'Your library is empty. Upload a selfie, a character or an animal.':'Preset characters are loading.';}
  const note=document.createElement('p');note.className='small';note.textContent=this.tab==='mine'?'Your uploads are private. Signed-in libraries are saved permanently; guest libraries expire after 7 days without a visit. Up to 50 images.':'32 original cartoon characters. Choosing an avatar only changes the current selfie; it is not carried into other places.';root.append(note);
 }
 headers(){return {'Content-Type':'application/json',...(this.session().csrf?{'X-CSRF-Token':this.session().csrf}:{})};}
 async rasterize(blob){const image=new Image(),url=URL.createObjectURL(blob);try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('Could not load this character'));image.src=url;});const canvas=document.createElement('canvas');canvas.width=canvas.height=768;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,768,768);context.drawImage(image,0,0,768,768);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Could not prepare this character')),'image/png'));}finally{URL.revokeObjectURL(url);}}
};
