/* Public threads: text is rendered as text, never interpreted as markup. */
const photoSocialCache=new Map();
window.PhotoScoutComments={clear(){photoSocialCache.clear();},create({resolve,request,headers,signIn,onReaction=()=>{},compact=false,commentsEnabled=true}){
 const box=document.createElement(compact?'details':'section');box.className='comment-thread';box.hidden=!commentsEnabled;
 const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const root=make('section',undefined,'comments-section'),actions=make('div',undefined,'social-actions'),like=make('button','♡ Like'),favorite=make('button','☆ Save');like.type=favorite.type='button';like.disabled=favorite.disabled=true;like.setAttribute('aria-pressed','false');favorite.setAttribute('aria-pressed','false');actions.append(like,favorite);const socialHint=make('p','','social-hint');socialHint.hidden=true;socialHint.setAttribute('role','status');root.append(actions,socialHint,box);root.thread=box;
 box.append(make(compact?'summary':'h3','Comments'));
 const status=make('p','','comment-status'),list=make('div',undefined,'comment-list'),more=make('button','Older comments','comment-more'),form=make('form',undefined,'comment-form'),input=make('textarea'),submit=make('button','Post comment'),login=make('button','Sign in to comment','comment-login');
 input.placeholder='Share a tip or your experience…';input.maxLength=2000;input.required=true;input.setAttribute('aria-label','Your comment');submit.type='submit';more.type=login.type='button';form.append(input,submit);box.append(status,list,more,form,login);form.hidden=login.hidden=more.hidden=true;status.setAttribute('role','status');
 let generation=0,targetKey=null,next=null,target=null,socialGeneration=0,socialTarget=null,socialData=null;
 const paintSocial=data=>{like.disabled=favorite.disabled=false;socialData=data;const state=data.threads[socialTarget.poi||'']||{likes:0,liked:false,favorited:false};like.textContent=(state.liked?'♥ Liked':'♡ Like')+(state.likes?' · '+state.likes:'');favorite.textContent=state.favorited?'★ Saved':'☆ Save';like.setAttribute('aria-pressed',String(state.liked));favorite.setAttribute('aria-pressed',String(state.favorited));};
 const refreshSocial=async()=>{const current=++socialGeneration;socialTarget=resolve();actions.hidden=!socialTarget&&!commentsEnabled;root.hidden=!commentsEnabled&&!socialTarget;socialHint.hidden=!!socialTarget||!commentsEnabled;socialHint.textContent=socialTarget?'':'Publish this photo to enable likes and saves.';if(!socialTarget){socialData=null;like.disabled=favorite.disabled=true;like.textContent='♡ Like';favorite.textContent='☆ Save';like.setAttribute('aria-pressed','false');favorite.setAttribute('aria-pressed','false');return;}try{let cached=photoSocialCache.get(socialTarget.id);if(!cached||Date.now()-cached.at>15000){cached={at:Date.now(),promise:request('/photo-scout/v1/publications/'+encodeURIComponent(socialTarget.id)+'/social')};photoSocialCache.set(socialTarget.id,cached);cached.promise.catch(()=>photoSocialCache.delete(socialTarget.id));}const data=await cached.promise;if(current===socialGeneration)paintSocial(data);}catch(error){if(current===socialGeneration){like.disabled=favorite.disabled=true;status.textContent=error.message;if(!commentsEnabled)root.append(status);}}};
 const react=async kind=>{if(!socialTarget)return;if(!socialData?.canReact){signIn();return;}const destination={...socialTarget},state=socialData.threads[destination.poi||'']||{},button=kind==='like'?like:favorite;button.disabled=true;try{const data=await request('/photo-scout/v1/publications/'+encodeURIComponent(destination.id)+'/reactions',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({kind,active:!(kind==='like'?state.liked:state.favorited),poiId:destination.poi||''})});photoSocialCache.set(destination.id,{at:Date.now(),promise:Promise.resolve(data)});if(socialTarget?.id===destination.id&&socialTarget?.poi===destination.poi)paintSocial(data);onReaction();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
 like.onclick=()=>react('like');favorite.onclick=()=>react('favorite');
 const path=()=>'/photo-scout/v1/publications/'+encodeURIComponent(target.id)+'/comments';
 const query=before=>'?' +new URLSearchParams({... (target.poi?{poiId:target.poi}:{}),...(before?{before:String(before)}:{})});
 const showItem=item=>{const row=make('article',undefined,'comment-item'),meta=make('div',undefined,'comment-meta');meta.append(make('strong',item.name),make('time',new Date(item.created*1000).toLocaleString()));row.append(meta,make('p',item.text));if(item.canDelete){const remove=make('button','Delete','comment-delete');remove.type='button';remove.onclick=async()=>{remove.disabled=true;try{await request(path()+'/'+encodeURIComponent(item.id),{method:'DELETE',headers:headers()});row.remove();if(!list.children.length)status.textContent='No comments yet. Be the first to share a tip.';}catch(error){status.textContent=error.message;remove.disabled=false;}};row.append(remove);}list.append(row);};
 const load=async(older=false)=>{const current=++generation;status.textContent='Loading comments…';more.disabled=true;try{const data=await request(path()+query(older?next:null));if(current!==generation)return;if(!older)list.replaceChildren();data.items.forEach(showItem);next=data.nextBefore;more.hidden=!next;form.hidden=!data.canComment;login.hidden=data.canComment;status.textContent=list.children.length?'':'No comments yet. Be the first to share a tip.';}catch(error){if(current===generation){status.textContent=error.message;form.hidden=login.hidden=more.hidden=true;targetKey=null;}}finally{if(current===generation)more.disabled=false;}};
 box.refreshComments=(force=false)=>{if(!commentsEnabled)return;if(compact&&!box.open)return;const resolved=resolve(),key=resolved?JSON.stringify(resolved):'';if(!force&&key===targetKey)return;generation++;target=resolved;targetKey=key;next=null;list.replaceChildren();form.hidden=login.hidden=more.hidden=true;if(!target){status.textContent='Publish this item to enable comments.';return;}load();};
 root.refreshComments=(force=false)=>{like.disabled=favorite.disabled=true;refreshSocial();box.refreshComments(force);};
 if(compact)box.addEventListener('toggle',()=>{if(box.open)box.refreshComments(true);});else queueMicrotask(()=>box.refreshComments());queueMicrotask(refreshSocial);
 more.onclick=()=>load(true);login.onclick=signIn;
 form.onsubmit=async event=>{event.preventDefault();const text=input.value.trim();if(!text||!target)return;const key=targetKey;submit.disabled=true;status.textContent='Posting…';try{await request(path(),{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({text,poiId:target.poi||''})});if(key!==targetKey)return;input.value='';await load();onReaction();}catch(error){if(key===targetKey)status.textContent=error.message;}finally{submit.disabled=false;}};
 return root;
}};
