// Small raster previews; no extra interactive map/WebGL instances in history rows.
(function(global){
 const W=96,H=72,CIRC=40075016.686,cache=new Map(),pending=new Map();let queue=Promise.resolve();
 const valid=n=>typeof n==='number'&&Number.isFinite(n);
 function area(entry){const c={...(entry.history?.result?.searchContext||{}),...(entry.task?.context||{})};return valid(c.lat)&&valid(c.lon)&&Math.abs(c.lat)<=85&&Math.abs(c.lon)<=180?{lat:c.lat,lon:c.lon,radius:Number(c.radius||entry.history?.radius||1000),label:c.locationLabel||'',...(c.routeGeometry||entry.history?.result?.route?{route:c.routeGeometry||entry.history.result.route}:{})}:null;}
 function geometry(a){if(a.route?.geometry?.coordinates?.length)return routeGeometry(a.route);const cos=Math.cos(a.lat*Math.PI/180),radius=Math.max(100,Math.min(20000,a.radius||1000)),z=Math.max(0,Math.min(16,Math.floor(Math.log2(CIRC*cos*16/(256*radius))))),size=256*2**z,sin=Math.sin(a.lat*Math.PI/180),x=(a.lon+180)/360*size,y=(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*size,left=x-W/2,top=y-H/2,tiles=[];
  for(let tx=Math.floor(left/256);tx<=Math.floor((left+W)/256);tx++)for(let ty=Math.floor(top/256);ty<=Math.floor((top+H)/256);ty++)if(ty>=0&&ty<2**z)tiles.push({z,x:((tx%2**z)+2**z)%2**z,y:ty,left:tx*256-left,top:ty*256-top});
  return {tiles,radius:radius/(CIRC*cos/size),width:W,height:H};
 }
 function routeGeometry(route){const points=route.geometry.coordinates.map(([lon,lat])=>[(lon+180)/360,(.5-Math.log((1+Math.sin(lat*Math.PI/180))/(1-Math.sin(lat*Math.PI/180)))/(4*Math.PI))]);for(let i=1;i<points.length;i++)points[i][0]+=Math.round(points[i-1][0]-points[i][0]);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),z=Math.max(0,Math.min(16,Math.floor(Math.log2(Math.min((W-24)/Math.max(1e-7,xmax-xmin),(H-24)/Math.max(1e-7,ymax-ymin))/256)))),size=256*2**z,left=(xmin+xmax)*size/2-W/2,top=(ymin+ymax)*size/2-H/2,tiles=[];for(let tx=Math.floor(left/256);tx<=Math.floor((left+W)/256);tx++)for(let ty=Math.floor(top/256);ty<=Math.floor((top+H)/256);ty++)if(ty>=0&&ty<2**z)tiles.push({z,x:((tx%2**z)+2**z)%2**z,y:ty,left:tx*256-left,top:ty*256-top});return {tiles,points:points.map(([x,y])=>[x*size-left,y*size-top]),width:W,height:H};}
 function thumbnail(a){const box=document.createElement('span');box.className='search-history-thumb';box.setAttribute('aria-hidden','true');if(!a){box.textContent='⌖';return box;}const g=geometry(a);
  for(const tile of g.tiles){const img=document.createElement('img');img.alt='';img.loading='lazy';img.decoding='async';img.src=`https://tile.openstreetmap.org/${tile.z}/${tile.x}/${tile.y}.png`;img.style.left=tile.left+'px';img.style.top=tile.top+'px';img.addEventListener('error',()=>{img.hidden=true;box.classList.add('map-unavailable');});box.append(img);}
  const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);
  if(g.points){const path=document.createElementNS(ns,'polyline');path.setAttribute('points',g.points.map(p=>p.join(',')).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#8060bd');path.setAttribute('stroke-width','3');svg.append(path);for(const p of [g.points[0],g.points.at(-1)]){const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',p[0]);dot.setAttribute('cy',p[1]);dot.setAttribute('r',3);dot.setAttribute('class','history-center-dot');svg.append(dot);}box.append(svg);return box;}
  for(const [radius,cls] of [[g.radius,'history-range-ring'],[3,'history-center-dot']]){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',W/2);circle.setAttribute('cy',H/2);circle.setAttribute('r',radius);circle.setAttribute('class',cls);svg.append(circle);}box.append(svg);return box;
 }
 function key(a){return a.lat.toFixed(5)+','+a.lon.toFixed(5);}
 try{for(const [k,v] of JSON.parse(localStorage.getItem('photo-scout-history-cities-v2')||'[]'))if(v.label&&v.expires>Date.now())cache.set(k,v);}catch{}
 function peek(a){const hit=cache.get(key(a));return hit&&hit.expires>Date.now()?hit.label:'';}
 function cityLabel(p){const city=p.city||(['city','town','village','hamlet'].includes(p.osm_value)?p.name:'');return city?[...new Set([city,p.state,p.country].filter(Boolean))].join(', '):'';}
 function city(a){const k=key(a),existing=cache.get(k);if(existing&&existing.expires>Date.now())return Promise.resolve(existing.label);if(pending.has(k))return pending.get(k);
  const task=queue.then(async()=>{let label='';try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch('https://photon.komoot.io/reverse?'+new URLSearchParams({lat:a.lat,lon:a.lon,lang:'en',limit:3}),{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(response.ok){const data=await response.json();label=(data.features||[]).map(f=>cityLabel(f.properties||{})).find(Boolean)||'';}}finally{clearTimeout(timer);}}catch{}
   cache.set(k,{label,expires:Date.now()+(label?7*86400000:10000)});while(cache.size>300)cache.delete(cache.keys().next().value);try{localStorage.setItem('photo-scout-history-cities-v2',JSON.stringify([...cache]));}catch{}return label;
  });pending.set(k,task);queue=task.then(()=>new Promise(resolve=>setTimeout(resolve,1000)));task.finally(()=>pending.delete(k));return task;
 }
 function hydrate(root){for(const item of root.querySelectorAll('.history-location[data-lat]')){if(item.dataset.loading)continue;item.dataset.loading='true';const a={lat:Number(item.dataset.lat),lon:Number(item.dataset.lon)};city(a).then(label=>{if(label&&item.isConnected){item.textContent=label;item.dataset.city=label;}delete item.dataset.loading;});}}
 global.PhotoScoutHistoryMap={area,geometry,thumbnail,peek,cityLabel,hydrate};
})(window);
